const data = {

    "login": "himansh7976",
    "id": 137978920,
    "node_id": "U_kgDOCDlkKA",
    "avatar_url": "https://avatars.githubusercontent.com/u/137978920?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/himansh7976",
    "html_url": "https://github.com/himansh7976",
    "followers_url": "https://api.github.com/users/himansh7976/followers",
    "following_url": "https://api.github.com/users/himansh7976/following{/other_user}",
    "gists_url": "https://api.github.com/users/himansh7976/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/himansh7976/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/himansh7976/subscriptions",
    "organizations_url": "https://api.github.com/users/himansh7976/orgs",
    "repos_url": "https://api.github.com/users/himansh7976/repos",
    "events_url": "https://api.github.com/users/himansh7976/events{/privacy}",
    "received_events_url": "https://api.github.com/users/himansh7976/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Himanshu verma",
    "company": null, 
    "blog": "",
    "location": null,
    "email": null,
    "hireable": null,
    "bio": null,
    "twitter_username": null,
    "public_repos": 17,
    "public_gists": 0,
    "followers": 0,
    "following": 1,
    "created_at": "2023-06-28T04:51:36Z",
    "updated_at": "2023-12-18T04:00:21Z"
    